import asyncio
import enum
import uuid
from collections.abc import AsyncGenerator

import niquests
from litestar import Router, get, post
from litestar.exceptions import HTTPException
from litestar.response import ServerSentEvent, Template
from litestar.types import SSEData

from guess_explainr import state
from guess_explainr.models import CompareRequest, ConfigRequest, ProcessUrlRequest

_MOCK_COUNTRIES = [
    "Germany",
    "France",
    "Netherlands",
    "Poland",
    "Austria",
    "Switzerland",
    "Belgium",
    "Denmark",
]

class ModelProvider(enum.Enum):
    OpenAI = "openai"
    Anthropic = "anthropic"
    Google = "google"

    async def load_model_list(self, key: str) -> list[str]:
        async with niquests.AsyncSession() as s:
            match self:
                case ModelProvider.OpenAI:
                    r = await s.get(
                        "https://api.openai.com/v1/models",
                        headers={"Authorization": f"Bearer {key}"},
                    )
                    r.raise_for_status()
                    _CHAT_PREFIXES = ("gpt-", "o1", "o3", "chatgpt-")
                    ids: list[str] = [
                        m["id"]
                        for m in r.json()["data"]
                        if any(m["id"].startswith(p) for p in _CHAT_PREFIXES)
                    ]
                    return sorted(ids)

                case ModelProvider.Anthropic:
                    r = await s.get(
                        "https://api.anthropic.com/v1/models",
                        headers={
                            "x-api-key": key,
                            "anthropic-version": "2023-06-01",
                        },
                    )
                    r.raise_for_status()
                    return [m["id"] for m in r.json()["data"]]

                case ModelProvider.Google:
                    r = await s.get(
                        "https://generativelanguage.googleapis.com/v1beta/models",
                        params={"key": key},
                    )
                    r.raise_for_status()
                    return [
                        m["name"].removeprefix("models/")
                        for m in r.json()["models"]
                        if "generateContent" in m.get("supportedGenerationMethods", [])
                    ]


@get("/models")
async def get_models(provider: str = "openai", api_key: str = "") -> Template:
    if not api_key:
        return Template(
            template_name="partials/models_options.html",
            context={"models": [], "placeholder": "Enter API key to load models…"},
        )
    try:
        models = await ModelProvider(provider).load_model_list(api_key)
    except Exception:
        return Template(
            template_name="partials/models_options.html",
            context={"models": [], "error": "Could not load models — check your API key"},
        )
    return Template(template_name="partials/models_options.html", context={"models": models})


@get("/config")
async def get_config() -> dict:
    return {"configured": state.get_config() is not None}


@post("/config")
async def save_config(data: ConfigRequest) -> Template:
    state.set_config({"provider": data.provider, "model": data.model})
    return Template(template_name="partials/config_success.html", context={})


@post("/process-url")
async def process_url(data: ProcessUrlRequest) -> Template:
    await asyncio.sleep(2.5)
    return Template(
        template_name="partials/step3_content.html",
        context={
            "country": "Germany",
            "available_countries": _MOCK_COUNTRIES,
        },
    )


@post("/compare")
async def compare(data: CompareRequest) -> Template:
    await asyncio.sleep(3.0)
    analysis_html = (
        "<p>This is a mock comparison analysis between "
        f"<strong>{data.country}</strong> and "
        f"<strong>{', '.join(data.compare_countries)}</strong>.</p>"
        "<p>Real analysis will be generated by the LLM once integrated.</p>"
    )
    context_text = f"{data.country} vs {', '.join(data.compare_countries)}"
    return Template(
        template_name="partials/step4_content.html",
        context={"analysis": analysis_html, "context": context_text},
    )


@get("/chat")
async def chat(message: str, context: str = "") -> ServerSentEvent:
    if not message:
        raise HTTPException(status_code=400, detail="message is required")

    async def _token_stream() -> AsyncGenerator[SSEData, None]:
        mock = (
            f"This is a mock response to: {message!r}. "
            "Real answers will come from the configured LLM. "
            "The context was: " + (context or "(none)") + "."
        )
        for word in mock.split():
            await asyncio.sleep(0.08)
            yield {"data": f"<span>{word} </span>", "event": "token"}
        yield {"data": "<span></span>", "event": "done"}

    return ServerSentEvent(_token_stream())


@get("/new-chat-id")
async def new_chat_id() -> dict:
    return {"id": str(uuid.uuid4())}


api_router = Router(
    path="/api",
    route_handlers=[get_models, get_config, save_config, process_url, compare, chat, new_chat_id],
)
