import asyncio

from litestar import post
from litestar.response import Template

from guess_explainr.models import CompareRequest


@post("/compare")
async def compare(data: CompareRequest) -> Template:
    await asyncio.sleep(3.0)
    analysis_html = (
        "<p>This is a mock comparison analysis between "
        f"<strong>{data.country}</strong> and "
        f"<strong>{', '.join(data.compare_countries)}</strong>.</p>"
        "<p>Real analysis will be generated by the LLM once integrated.</p>"
    )
    context_text = f"{data.country} vs {', '.join(data.compare_countries)}"
    return Template(
        template_name="partials/step4_content.html",
        context={"analysis": analysis_html, "context": context_text},
    )
