import asyncio
import uuid
from collections.abc import AsyncGenerator

from litestar import Router, get, post
from litestar.exceptions import HTTPException
from litestar.response import ServerSentEvent, Template
from litestar.types import SSEData

from geolearnr import state
from geolearnr.models import CompareRequest, ConfigRequest, ProcessUrlRequest

_MOCK_COUNTRIES = [
    "Germany",
    "France",
    "Netherlands",
    "Poland",
    "Austria",
    "Switzerland",
    "Belgium",
    "Denmark",
]

_MODELS_BY_PROVIDER: dict[str, list[dict[str, str]]] = {
    "openai": [
        {"id": "gpt-4o", "name": "GPT-4o"},
        {"id": "gpt-4o-mini", "name": "GPT-4o Mini"},
    ],
    "anthropic": [
        {"id": "claude-opus-4-6", "name": "Claude Opus 4.6"},
        {"id": "claude-sonnet-4-6", "name": "Claude Sonnet 4.6"},
    ],
    "google": [
        {"id": "gemini-2.0-flash", "name": "Gemini 2.0 Flash"},
        {"id": "gemini-2.5-pro", "name": "Gemini 2.5 Pro"},
    ],
}


@get("/models")
async def get_models(provider: str = "openai") -> Template:
    models = _MODELS_BY_PROVIDER.get(provider, [])
    return Template(template_name="partials/models_options.html", context={"models": models})


@get("/config")
async def get_config() -> dict:
    return {"configured": state.get_config() is not None}


@post("/config")
async def save_config(data: ConfigRequest) -> Template:
    state.set_config({"provider": data.provider, "model": data.model})
    return Template(template_name="partials/config_success.html", context={})


@post("/process-url")
async def process_url(data: ProcessUrlRequest) -> Template:
    await asyncio.sleep(2.5)
    return Template(
        template_name="partials/step3_content.html",
        context={
            "country": "Germany",
            "available_countries": _MOCK_COUNTRIES,
        },
    )


@post("/compare")
async def compare(data: CompareRequest) -> Template:
    await asyncio.sleep(3.0)
    analysis_html = (
        "<p>This is a mock comparison analysis between "
        f"<strong>{data.country}</strong> and "
        f"<strong>{', '.join(data.compare_countries)}</strong>.</p>"
        "<p>Real analysis will be generated by the LLM once integrated.</p>"
    )
    context_text = f"{data.country} vs {', '.join(data.compare_countries)}"
    return Template(
        template_name="partials/step4_content.html",
        context={"analysis": analysis_html, "context": context_text},
    )


@get("/chat")
async def chat(message: str, context: str = "") -> ServerSentEvent:
    if not message:
        raise HTTPException(status_code=400, detail="message is required")

    async def _token_stream() -> AsyncGenerator[SSEData, None]:
        mock = (
            f"This is a mock response to: {message!r}. "
            "Real answers will come from the configured LLM. "
            "The context was: " + (context or "(none)") + "."
        )
        for word in mock.split():
            await asyncio.sleep(0.08)
            yield {"data": f"<span>{word} </span>", "event": "token"}
        yield {"data": "<span></span>", "event": "done"}

    return ServerSentEvent(_token_stream())


@get("/new-chat-id")
async def new_chat_id() -> dict:
    return {"id": str(uuid.uuid4())}


api_router = Router(
    path="/api",
    route_handlers=[get_models, get_config, save_config, process_url, compare, chat, new_chat_id],
)
