import dataclasses

from pydantic_ai import Agent, RunContext

from guess_explainr import state


@dataclasses.dataclass(frozen=True)
class AgentDependency:
    compare_country_ids: list[str]
    user_questions: str


def run_analysis(
    compare_country_ids: list[str],
    user_questions: str,
) -> str:
    state_config = state.get_config()
    prompt = (
        "You are an experienced teacher of the game GeoGuessr.\n"
        "You will be provided an image of a Google Street View location and a task to explain to "
        "the user,so that they can learn to become better at the game from it.\n"
        "\n"
        "You will also be provided with a set of relevant guides.\n"
        "These explain clues that might be used by players of the game to "
        "distinguish locations from another.\n"
        "Base all your analysis and explanations on content provided by these guides.\n"
    )
    agent = Agent(
        f"{state_config.ai_provider}:{state_config.ai_model}",
        deps_type=AgentDependency,
        instructions=prompt,
    )

    @agent.instructions
    def task(ctx: RunContext[AgentDependency]) -> str:
        return (
            f"You will be given guides for the following countries: {compare_country_ids}. "
            f"Only consider these as options for where the location might be. "
            f"The user also asked: {user_questions}"
        )

    return (
        "<p>This is a mock comparison analysis between "
        f"<strong>{', '.join(compare_country_ids)}</strong>.</p>"
        "<p>Real analysis will be generated by the LLM once integrated.</p>"
    )
